// othdispa.h
// Dispatch indices for Othello ObjectWindows interface
// (C) Copyright 1994 by Tom Weatherhead

// COMMANDS in owlrc.h ??
// #define COMMANDS		200
#define CM_FILEEXIT		201
#define CM_GAMEOPTIONS		202
#define CM_GAMEPLAY		203
#define CM_ABOUT		204

#define ID_XHUMANBTN		101
#define ID_XCOMPBTN		102
#define ID_XPLAYERBOX		103
#define ID_XLEVELEDIT		104
#define ID_OHUMANBTN		105
#define ID_OCOMPBTN		106
#define ID_OPLAYERBOX		107
#define ID_OLEVELEDIT		108

// ******** End of othdispa.h ********
